title: "My Report"
author: "Aditi"
logo: "logo.png"

# This specifies where your notebook source files are.
# This single repository section is enough.
repository:
  url: "https://github.com/Aditi200122/report_jupyter_books"
  branch: "main"

html_theme_options:
  launch_buttons:
    binderhub_url: "https://mybinder.org"
    colab_url: "https://colab.research.google.com"
    thebe: true
  use_repository_button: true # This option adds a button to go to your repository.

execute:
  execute_notebooks: "force"

sphinx:
  config:
    html_js_files:
      - https://cdn.plot.ly/plotly-latest.min.js