title: My sample book
author: Aditi
logo: logo.png

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/Aditi200122/report_jupyter_books
  # path_to_book: docs
  branch: master

html:
  favicon: ""
  use_issues_button: true
  use_repository_button: true
  use_jupyterlab_widgets: true   # ENABLE ipywidgets

launch_buttons:
  thebe: true
  binderhub_url: https://mybinder.org
  colab: true 
  interactive: true

sphinx:
  config:
    html_js_files:
      - https://cdn.plot.ly/plotly-latest.min.js
