title: My sample book
author: Aditi
logo: logo.png

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/Aditi200122/report_jupyter_books
  branch: master

html:
  use_repository_button: true
  use_issues_button: true
  use_jupyterlab_widgets: true

html_theme_options:
  launch_buttons:
    thebe: true
    notebook_interface: "classic"  # or "jupyterlab"

thebe:
  use_jupyterlite: true   # This is the key for instant in-browser kernel

sphinx:
  config:
    html_js_files:
      - https://cdn.plot.ly/plotly-latest.min.js
