title: "My Report"
author: "Aditi"
logo: "logo.png"

repository:
  url: "https://github.com/Aditi200122/report_jupyter_books"
  branch: "main"

html:
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true

html_theme_options:
  launch_buttons:
    binderhub_url: "https://mybinder.org"
    colab_url: "https://colab.research.google.com"
    thebe: true
    notebook_interface: "jupyterlab"

execute:
  execute_notebooks: "force"

thebe:
  binderhub_url: "https://mybinder.org"
  repository_url: "https://github.com/Aditi200122/report_jupyter_books"
  branch: "main"

sphinx:
  config:
    html_js_files:
      - https://cdn.plot.ly/plotly-latest.min.js
