title: "My Report"
author: "Aditi"
logo: "logo.png"
#repository
repository:
  url: "https://github.com/Aditi200122/report_jupyter_books"
  branch: "main"
#html
html_theme_options:
  launch_buttons:
    binderhub_url: "https://mybinder.org"
    colab_url: "https://colab.research.google.com"
    thebe: true
  use_repository_button: true
#execute
execute:
  execute_notebooks: "force"
#sphinx
sphinx:
  config:
    html_js_files:
      - https://cdn.plot.ly/plotly-latest.min.js