title: "My Report"
author: "Aditi"
logo: "logo.png"

# This specifies where your notebook source files are.
# In your case, it's the top-level directory.
repository:
  url: "https://github.com/Aditi200122/report_jupyter_books"
  branch: "main" # or 'master' depending on your branch name

html_theme_options:
  launch_buttons:
    binderhub_url: "https://mybinder.org"
    colab_url: "https://colab.research.google.com"
    thebe: true
  repository_url: "https://github.com/Aditi200122/report_jupyter_books"
  repository_branch: "main" # or "master"

# Other configurations you might want to include.
execute:
  execute_notebooks: "force"

# Specify a requirements file for Binder and Thebe to use.
# You need to create this file in your repository.
sphinx:
  config:
    html_js_files:
      - https://cdn.plot.ly/plotly-latest.min.js